name: List files in Drive
on:
  push:
    branches:
      - master
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: List files in Google Drive folder
        uses: hworr93/upload-to-drive@master
        id: list
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: list
          googleFolderId: 1Z2JWpEG0NGkBwKINUGAc7CbrSG8jtHiR
      - name: Print folder files
        run: echo "${{ steps.list.outputs.folderFiles }}"
