name: Upload to Drive
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Upload file to Google Drive
        uses: hworr93/upload-to-drive@master
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: upload
          localPath: ./example.txt
          googleFolderId: 1Z2JWpEG0NGkBwKINUGAc7CbrSG8jtHiR
